/*
  * Copyright 2026 Twilight
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *   http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
*/
#pragma once

/**
 * @file spriteart.h
 * @brief GENERATED by scripts/import_sprites.py -- do not edit by hand.
 *
 * How many 16x16 frames each overworld sprite's artwork holds.
 *
 *   6  a WALKING person: stand down, stand up, stand LEFT, then the three walking
 *      frames. There is no right-facing frame -- the game draws right as left,
 *      X-flipped.
 *   3  a STILL person: stand down, stand up, stand left. No walk cycle was ever
 *      drawn for them (the Game Boy's sprite budget is 9 walking + 2 still).
 *   1  a ball / boulder / fossil: the game's facing table sends every facing and
 *      every animation frame to the same quad.
 *
 * Indexed by picture id (1-based); index 0 is a placeholder so the ids read straight.
 * The artwork itself is one atlas: :/assets/sprites/overworld.png, 72 cells of
 * 16x96 px, cell (id - 1). See notes/reference/sprites.md.
 */

constexpr int spriteArtCount = 72;

constexpr int spriteArtFrames[72 + 1] = {
  0,   //  0  (not a sprite -- picture id 0 means the slot is unused)
  6,   //  1  Player
  6,   //  2  Rival
  6,   //  3  Prof. Oak
  6,   //  4  Bug Catcher
  6,   //  5  Slowbro
  6,   //  6  Lass
  6,   //  7  Black Hair Boy 1
  6,   //  8  Little Girl
  6,   //  9  Bird
  6,   // 10  Fat Bald Guy
  6,   // 11  Gambler
  6,   // 12  Black Hair Boy 2
  6,   // 13  Girl
  6,   // 14  Hiker
  6,   // 15  Foulard Woman
  6,   // 16  Gentleman
  6,   // 17  Daisy
  6,   // 18  Biker
  6,   // 19  Sailor
  6,   // 20  Cook
  3,   // 21  Bike Shop Guy
  6,   // 22  Mr. Fuji
  6,   // 23  Giovanni
  6,   // 24  Rocket
  6,   // 25  Medium
  6,   // 26  Waiter
  6,   // 27  Erika
  6,   // 28  Mom Geisha
  6,   // 29  Brunette Girl
  6,   // 30  Lance
  6,   // 31  Oak Scientist Aide
  6,   // 32  Oak Aide
  6,   // 33  Rocker
  6,   // 34  Swimmer
  3,   // 35  White Player
  3,   // 36  Gym Helper
  3,   // 37  Old Person
  3,   // 38  Mart Guy
  3,   // 39  Fisher
  3,   // 40  Old Medium Woman
  3,   // 41  Nurse
  3,   // 42  Cable Club Woman
  3,   // 43  Mr. Masterball
  3,   // 44  Lapras Giver
  3,   // 45  Warden
  3,   // 46  SS. Captain
  6,   // 47  Fisher 2
  6,   // 48  Blackbelt
  3,   // 49  Guard
  3,   // 50  Cop Guard
  3,   // 51  Mom
  3,   // 52  Balding Guy
  3,   // 53  Young Boy
  3,   // 54  Gameboy Kid
  3,   // 55  Gameboy Kid Copy
  6,   // 56  Clefairy
  6,   // 57  Agatha
  6,   // 58  Bruno
  6,   // 59  Lorelei
  6,   // 60  Seel
  1,   // 61  Pokeball
  1,   // 62  Omanyte
  1,   // 63  Boulder
  1,   // 64  Paper Sheet
  1,   // 65  Book Map Dex
  1,   // 66  Clipboard
  1,   // 67  Snorlax
  1,   // 68  Old Amber Copy
  1,   // 69  Old Amber
  1,   // 70  Lying Old Man Unused 1
  1,   // 71  Lying Old Man Unused 2
  1,   // 72  Lying Old Man
};
