/*
  * Copyright 2026 Twilight
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *   http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
*/
#pragma once

/**
 * @file spriteart.h
 * @brief GENERATED by scripts/import_sprites.py -- do not edit by hand.
 *
 * Every overworld sprite's artwork: WHERE it is, and how many 16x16 frames it holds.
 *
 *   6  a WALKING person: stand down, stand up, stand LEFT, then the three walking
 *      frames. There is no right-facing frame -- the game draws right as left,
 *      X-flipped.
 *   3  a STILL person: stand down, stand up, stand left. No walk cycle was ever
 *      drawn for them (the Game Boy's sprite budget is 9 walking + 2 still).
 *   1  a ball / boulder / fossil: the game's facing table sends every facing and
 *      every animation frame to the same quad.
 *
 * Indexed by picture id (1-based); index 0 is a placeholder so the ids read straight.
 *
 * ⚠️ ONE LOOSE FILE PER SPRITE, deliberately -- NOT an atlas (Twilight). Loose files are
 * far easier to work with, and 72 tiny PNGs in a Qt resource cost nothing to load.
 *
 * See notes/reference/sprites.md.
 */

struct SpriteArt {
  const char* file;   ///< Its own PNG. Open it, look at it, replace it.
  int frames;         ///< 6 (walks) / 3 (still person) / 1 (an object).
};

constexpr int spriteArtCount = 72;

constexpr SpriteArt spriteArt[72 + 1] = {
  { "", 0 },   //  0  (not a sprite -- picture id 0 means the slot is unused)
  { ":/assets/sprites/01_player.png", 6 },          //  1  Player
  { ":/assets/sprites/02_rival.png", 6 },           //  2  Rival
  { ":/assets/sprites/03_prof_oak.png", 6 },        //  3  Prof. Oak
  { ":/assets/sprites/04_bug_catcher.png", 6 },     //  4  Bug Catcher
  { ":/assets/sprites/05_slowbro.png", 6 },         //  5  Slowbro
  { ":/assets/sprites/06_lass.png", 6 },            //  6  Lass
  { ":/assets/sprites/07_black_hair_boy_1.png", 6 },//  7  Black Hair Boy 1
  { ":/assets/sprites/08_little_girl.png", 6 },     //  8  Little Girl
  { ":/assets/sprites/09_bird.png", 6 },            //  9  Bird
  { ":/assets/sprites/10_fat_bald_guy.png", 6 },    // 10  Fat Bald Guy
  { ":/assets/sprites/11_gambler.png", 6 },         // 11  Gambler
  { ":/assets/sprites/12_black_hair_boy_2.png", 6 },// 12  Black Hair Boy 2
  { ":/assets/sprites/13_girl.png", 6 },            // 13  Girl
  { ":/assets/sprites/14_hiker.png", 6 },           // 14  Hiker
  { ":/assets/sprites/15_foulard_woman.png", 6 },   // 15  Foulard Woman
  { ":/assets/sprites/16_gentleman.png", 6 },       // 16  Gentleman
  { ":/assets/sprites/17_daisy.png", 6 },           // 17  Daisy
  { ":/assets/sprites/18_biker.png", 6 },           // 18  Biker
  { ":/assets/sprites/19_sailor.png", 6 },          // 19  Sailor
  { ":/assets/sprites/20_cook.png", 6 },            // 20  Cook
  { ":/assets/sprites/21_bike_shop_guy.png", 3 },   // 21  Bike Shop Guy
  { ":/assets/sprites/22_mr_fuji.png", 6 },         // 22  Mr. Fuji
  { ":/assets/sprites/23_giovanni.png", 6 },        // 23  Giovanni
  { ":/assets/sprites/24_rocket.png", 6 },          // 24  Rocket
  { ":/assets/sprites/25_medium.png", 6 },          // 25  Medium
  { ":/assets/sprites/26_waiter.png", 6 },          // 26  Waiter
  { ":/assets/sprites/27_erika.png", 6 },           // 27  Erika
  { ":/assets/sprites/28_mom_geisha.png", 6 },      // 28  Mom Geisha
  { ":/assets/sprites/29_brunette_girl.png", 6 },   // 29  Brunette Girl
  { ":/assets/sprites/30_lance.png", 6 },           // 30  Lance
  { ":/assets/sprites/31_oak_scientist_aide.png", 6 },// 31  Oak Scientist Aide
  { ":/assets/sprites/32_oak_aide.png", 6 },        // 32  Oak Aide
  { ":/assets/sprites/33_rocker.png", 6 },          // 33  Rocker
  { ":/assets/sprites/34_swimmer.png", 6 },         // 34  Swimmer
  { ":/assets/sprites/35_white_player.png", 3 },    // 35  White Player
  { ":/assets/sprites/36_gym_helper.png", 3 },      // 36  Gym Helper
  { ":/assets/sprites/37_old_person.png", 3 },      // 37  Old Person
  { ":/assets/sprites/38_mart_guy.png", 3 },        // 38  Mart Guy
  { ":/assets/sprites/39_fisher.png", 3 },          // 39  Fisher
  { ":/assets/sprites/40_old_medium_woman.png", 3 },// 40  Old Medium Woman
  { ":/assets/sprites/41_nurse.png", 3 },           // 41  Nurse
  { ":/assets/sprites/42_cable_club_woman.png", 3 },// 42  Cable Club Woman
  { ":/assets/sprites/43_mr_masterball.png", 3 },   // 43  Mr. Masterball
  { ":/assets/sprites/44_lapras_giver.png", 3 },    // 44  Lapras Giver
  { ":/assets/sprites/45_warden.png", 3 },          // 45  Warden
  { ":/assets/sprites/46_ss_captain.png", 3 },      // 46  SS. Captain
  { ":/assets/sprites/47_fisher_2.png", 6 },        // 47  Fisher 2
  { ":/assets/sprites/48_blackbelt.png", 6 },       // 48  Blackbelt
  { ":/assets/sprites/49_guard.png", 3 },           // 49  Guard
  { ":/assets/sprites/50_cop_guard.png", 3 },       // 50  Cop Guard
  { ":/assets/sprites/51_mom.png", 3 },             // 51  Mom
  { ":/assets/sprites/52_balding_guy.png", 3 },     // 52  Balding Guy
  { ":/assets/sprites/53_young_boy.png", 3 },       // 53  Young Boy
  { ":/assets/sprites/54_gameboy_kid.png", 3 },     // 54  Gameboy Kid
  { ":/assets/sprites/55_gameboy_kid_copy.png", 3 },// 55  Gameboy Kid Copy
  { ":/assets/sprites/56_clefairy.png", 6 },        // 56  Clefairy
  { ":/assets/sprites/57_agatha.png", 6 },          // 57  Agatha
  { ":/assets/sprites/58_bruno.png", 6 },           // 58  Bruno
  { ":/assets/sprites/59_lorelei.png", 6 },         // 59  Lorelei
  { ":/assets/sprites/60_seel.png", 6 },            // 60  Seel
  { ":/assets/sprites/61_pokeball.png", 1 },        // 61  Pokeball
  { ":/assets/sprites/62_omanyte.png", 1 },         // 62  Omanyte
  { ":/assets/sprites/63_boulder.png", 1 },         // 63  Boulder
  { ":/assets/sprites/64_paper_sheet.png", 1 },     // 64  Paper Sheet
  { ":/assets/sprites/65_book_map_dex.png", 1 },    // 65  Book Map Dex
  { ":/assets/sprites/66_clipboard.png", 1 },       // 66  Clipboard
  { ":/assets/sprites/67_snorlax.png", 1 },         // 67  Snorlax
  { ":/assets/sprites/68_old_amber_copy.png", 1 },  // 68  Old Amber Copy
  { ":/assets/sprites/69_old_amber.png", 1 },       // 69  Old Amber
  { ":/assets/sprites/70_lying_old_man_unused_1.png", 1 },// 70  Lying Old Man Unused 1
  { ":/assets/sprites/71_lying_old_man_unused_2.png", 1 },// 71  Lying Old Man Unused 2
  { ":/assets/sprites/72_lying_old_man.png", 1 },   // 72  Lying Old Man
};
