#!/usr/bin/env python3
"""Event-flag scenario TEST RUNNER — single-shot, self-terminating, robust.

The reliable pattern (same as scripts/emu/dump_state.py, which tst_emu_parity
drives): boot PyBoy in ONE process, do the work, write results to a file, and
EXIT. No persistent session, no IPC, no interactive driving — those are what made
earlier attempts fragile (accumulating zombie processes, poll races). Each
scenario gets its OWN PyBoy instance that is ALWAYS stopped in a `finally`, and
every loop is frame-bounded so nothing can hang.

Reads a scenarios JSON, forges a save for each (any map/pos/flags), boots on
Continue, optionally drives the player, and classifies the outcome:
    healthy  — reached & stayed on a sane overworld / battle
    crash    — went to garbage (insane map dims / dead tilemap) => a real crash
    no-boot  — never reached the overworld (crash on load, or bad forge)
    hang     — assigned BY THE OWNER (tst_flag_scenarios / the dev MCP server)
               when this process never returns: a hard-crashed console executes
               STOP, the clocks halt, the frame never completes, and PyBoy's
               tick() spins forever (reproduced 2026-07-16). This process cannot
               classify its own wedge — the owner's timeout + TREE-kill is the
               watchdog (the venv python.exe is a launcher; kill its tree, not it).

Cross-map scenarios use CONSOLE-AUTHORED base saves: a scenario with a "map" is
built on tmp/emu/map-saves/map<id>.sav, generated by forge_map_save.py (the game
itself walks there through a hijacked door and the settled WRAM is dumped —
every pointer authored by the engine). Missing bases are generated on the fly in
a FRESH subprocess (one PyBoy per process; this process boots its own only after
that child exits). Coordinates relocate with the derived bytes kept in sync
(block coords + view pointer). A bare map-id poke — the old way — is a CHIMERA
that wedges the console, and forge() now refuses it.

Exit codes: 0 ok · 2 unavailable (no ROM / not run under the emu venv).

Usage (run under tmp/emu-venv/Scripts/python.exe):
    python run_flag_scenarios.py [--scenarios scripts/emu/flag_scenarios.json]
                                 [--out tmp/emu/flag_scenarios_result.json]
"""
from __future__ import annotations
import argparse
import atexit
import json
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROM = REPO / "assets" / "references" / "backup.gb"
BASE_SAV = REPO / "assets" / "saves" / "natural-clean" / "BaseSAV.sav"
CANON = REPO / "tmp" / "event-flags" / "event_flags_canonical.json"
MAP_SAVES = REPO / "tmp" / "emu" / "map-saves"

EV_START, EV_LEN = 0x29F3, 0x140
SAV_CUR_MAP, SAV_Y, SAV_X = 0x260A, 0x260D, 0x260E
CK, CK0, CKN = 0x3523, 0x2598, 0xF8B

W_MAP, W_W, W_H, W_Y, W_X, W_BATTLE = 0xD35E, 0xD369, 0xD368, 0xD361, 0xD362, 0xD057
W_OVERWORLD, W_TILEMAP = 0xC6E8, 0xC3A0
SCREEN = 20 * 18

_LIVE = {"pb": None}
atexit.register(lambda: _LIVE["pb"] and _LIVE["pb"].stop(save=False))


def name_to_index():
    if not CANON.exists():
        return {}
    return {r["name"]: r["index"] for r in json.loads(CANON.read_text(encoding="utf-8"))
            if r["name"]}


def map_base(map_id: int) -> bytes:
    """The console-authored base save for a map — generated in a fresh subprocess
    if not cached (forge_map_save.py; one PyBoy per process, always)."""
    cache = MAP_SAVES / f"map{map_id:03d}.sav"
    if not cache.exists():
        r = subprocess.run([sys.executable,
                            str(REPO / "scripts" / "emu" / "forge_map_save.py"),
                            "--map", str(map_id)],
                           capture_output=True, text=True, timeout=420, cwd=str(REPO))
        if r.returncode != 0 or not cache.exists():
            raise RuntimeError(f"map base generation failed for {map_id:#04x}:\n"
                               f"{r.stdout}{r.stderr}")
    return cache.read_bytes()


sys.path.insert(0, str(Path(__file__).resolve().parent))
from forge_save import forge as fs_forge  # noqa: E402  (the ONE shared forge)


def forge_for(sc, base_default: bytes) -> bytes:
    """Build the scenario's save: console-authored map base when 'map' is given,
    coords through relocate() (derived bytes stay in sync), then the flags, the
    per-map script steps ('scripts': {"Route 22": 0}) and the filter flags
    ('filterFlags': {"Route 22/Rival 1": "show"})."""
    mid = sc.get("map")
    mid = int(mid, 16) if isinstance(mid, str) else mid
    base = map_base(mid) if mid is not None else base_default
    flags = sc.get("flags", [])
    return fs_forge(base,
                    y=sc.get("y"), x=sc.get("x"),
                    flag_names=None if flags == "ALL" else (flags or None),
                    all_flags=flags == "ALL",
                    scripts=sc.get("scripts"),
                    filter_flags=sc.get("filterFlags"))


def on_overworld(pb):
    m = pb.memory
    w, h = m[W_W], m[W_H]
    if not (0 < w <= 64 and 0 < h <= 96):
        return False
    blocks = bytes(m[W_OVERWORLD:W_OVERWORLD + (w + 6) * (h + 6)])
    screen = bytes(m[W_TILEMAP:W_TILEMAP + SCREEN])
    return len(set(blocks)) > 1 and len(set(screen)) > 1


def sane(pb):
    if on_overworld(pb):
        return True
    m = pb.memory
    if m[W_BATTLE] in (1, 2):
        return len(set(bytes(m[W_TILEMAP:W_TILEMAP + SCREEN]))) > 1
    return False


def boot(pb, budget=4000):
    f = 0
    while f < budget and not on_overworld(pb):
        pb.button("start" if (f // 24) % 2 == 0 else "a", delay=8)
        for _ in range(24):
            pb.tick()
        f += 24
    return on_overworld(pb), f


def run_scenario(sc, base, name_idx, PyBoy, out_rom):
    sav = forge_for(sc, base)
    (out_rom.parent / "rom.gb.ram").write_bytes(sav)
    pb = PyBoy(str(out_rom), window="null", sound_emulated=False)
    _LIVE["pb"] = pb
    try:
        booted, frames = boot(pb)
        if not booted:
            return {"name": sc["name"], "result": "no-boot", "frames": frames}
        entered_battle = False
        crash_step = None
        for spec in sc.get("drive", []):
            d, n = spec.split(":")
            for step in range(int(n)):
                pb.button(d, delay=4)
                for _ in range(10):
                    pb.tick()
                if pb.memory[W_BATTLE] in (1, 2):
                    entered_battle = True
                if not sane(pb):
                    crash_step = f"{d}:{step}"
                    break
            if crash_step:
                break
        # settle + final health check
        for _ in range(120):
            pb.tick()
        result = "healthy" if sane(pb) and crash_step is None else "crash"
        return {"name": sc["name"], "result": result, "map": pb.memory[W_MAP],
                "battle": entered_battle, "crash_at": crash_step,
                "expect": sc.get("expect")}
    finally:
        pb.stop(save=False)
        _LIVE["pb"] = None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenarios", default=str(REPO / "scripts" / "emu" / "flag_scenarios.json"))
    ap.add_argument("--out", default=str(REPO / "tmp" / "emu" / "flag_scenarios_result.json"))
    ap.add_argument("--only", default=None,
                    help="run just this scenario by name (PyBoy is not safe to "
                         "re-instantiate in one process, so batches are best run "
                         "one scenario per process)")
    a = ap.parse_args()

    if not ROM.exists():
        sys.stderr.write("no ROM at assets/references/backup.gb (local-only)\n")
        return 2
    try:
        from pyboy import PyBoy
    except ImportError:
        sys.stderr.write("PyBoy not installed — run under tmp/emu-venv\n")
        return 2

    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out_rom = out.parent / "rom.gb"
    out_rom.write_bytes(ROM.read_bytes())

    scenarios = json.loads(Path(a.scenarios).read_text(encoding="utf-8"))
    if a.only:
        scenarios = [s for s in scenarios if s.get("name") == a.only]
    base = BASE_SAV.read_bytes()
    name_idx = name_to_index()

    results = []
    started = time.time()
    for sc in scenarios:
        try:
            r = run_scenario(sc, base, name_idx, PyBoy, out_rom)
        except Exception as e:  # one bad scenario never kills the batch
            r = {"name": sc.get("name", "?"), "result": "error", "error": repr(e)}
        results.append(r)
        out.write_text(json.dumps({"elapsed": round(time.time() - started, 1),
                                   "results": results}, indent=1))
        print(r, flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
