/*
  * Copyright 2019 Twilight
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *   http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
*/

/**
 * @file boot.cpp
 * @brief The bootstrap sequence: bootDatabase() -> bootQmlLinkage() ->
 *        Router::loadScreens() -> createApp() (QApplication + MainWindow).
 *        Returns a ready-to-exec QApplication to main().
 */

#include <QApplication>
#include <QIcon>
#include <QElapsedTimer>
#include <QDebug>
#include <QTranslator>
#include <QLocale>
#include <QSettings>
#include <QLibraryInfo>

#include "../../ui/window/mainwindow.h"
#include "../bridge/router.h"

// Generated by CMake from the repo-root VERSION; provides PSE_VERSION_FULL
// (e.g. "0.7.0-alpha+g1a2b3c4d"). See notes/reference/versioning.md.
#include "pse_version.h"

extern void bootDatabase();
extern void bootQmlLinkage();
extern void applyDebugLaunch(QApplication* app); // DEBUG-only launch flags (no-op in release)
extern void startDebugServer();                  // DEBUG-only live control channel (no-op in release)

// There is only ever one main window.
MainWindow* mainWindow = nullptr;

// Installs the UI translators, before any QML is instantiated, so qsTr()/tr()
// resolve to the chosen language at load time.
//
// Language preference resolves as: an explicit "ui/language" setting (a locale
// name like "fr" or "de"), else the system locale. English is the source
// language, so when no .qm matches — or a particular string is untranslated —
// the UI simply falls back to the source text. That graceful degradation is by
// design (see notes/context/principles.md): a missing translation never blanks
// a label or blocks the user. See notes/reference/i18n.md for the pipeline.
static void installTranslators(QApplication* app)
{
  QSettings settings; // uses the org/app names set in createApp()
  const QString pref = settings.value(QStringLiteral("ui/language")).toString();
  const QLocale locale = pref.isEmpty() ? QLocale::system() : QLocale(pref);

  // The app's own strings (translations/pse_<locale>.ts → :/i18n/pse_<locale>.qm).
  auto* appTr = new QTranslator(app);
  if (appTr->load(locale, QStringLiteral("pse"), QStringLiteral("_"),
                  QStringLiteral(":/i18n")))
    app->installTranslator(appTr);
  else
    delete appTr; // no catalog for this locale — stay on the en_US source strings

  // Qt's own built-in strings (standard dialog buttons, etc.), best-effort.
  auto* qtTr = new QTranslator(app);
  if (qtTr->load(locale, QStringLiteral("qtbase"), QStringLiteral("_"),
                 QLibraryInfo::path(QLibraryInfo::TranslationsPath)))
    app->installTranslator(qtTr);
  else
    delete qtTr;
}

// Sets critical Qt options that must be configured before QApplication is created.
static void preBootAttributes()
{
  // Qt 6: High-DPI scaling is enabled automatically — no setAttribute needed.
  // Qt 6: AA_CompressHighFrequencyEvents and AA_CompressTabletEvents are on by default.
  // Qt 6: AA_DisableWindowContextHelpButton is the default on all platforms.
  // Nothing to set here — kept as a hook for future platform-specific tweaks.
}

// Creates and configures the QApplication instance.
[[nodiscard]] static QApplication* createApp(int argc, char* argv[])
{
  preBootAttributes();

  QApplication::setApplicationName("Pokered Save Editor");
  QApplication::setOrganizationName("Twilight");
  QApplication::setApplicationVersion(QStringLiteral(PSE_VERSION_FULL));
  QApplication::setOrganizationDomain("pokeredsaveeditor.twilight.app");

  // Note: Do NOT set a custom QSurfaceFormat with MSAA here.
  // QQuickWidget renders into an offscreen FBO; requesting MSAA via
  // setDefaultFormat() causes the scene graph to hang on context creation
  // on many Windows drivers. Qt Quick handles its own antialiasing internally.

  auto* app = new QApplication(argc, argv);

  // Install translators right after the app exists and before the MainWindow
  // (and thus any QML) is created, so qsTr()/tr() resolve at load time.
  installTranslators(app);

  qSetMessagePattern("[%{type}]: %{message} ~ %{time} %{file} %{function} %{line}");

  app->setWindowIcon(QIcon("qrc:/assets/icons/app/512x512.png"));

  // Qt 6 uses QRandomGenerator internally; no manual seeding required.

  mainWindow = new MainWindow();

  // DEBUG: --minimized starts the window minimized (background) so automation can
  // open + drive + screenshot the app without it popping up / stealing focus. The
  // QQuickWidget framebuffer grab still works while minimized, so --shot is unaffected.
#ifdef QT_DEBUG
  if(app->arguments().contains(QStringLiteral("--minimized")))
    mainWindow->showMinimized();
  else
    mainWindow->show();
#else
  mainWindow->show();
#endif

  return app;
}

// Performs full program bootstrapping and returns a ready-to-exec QApplication.
extern QApplication* boot(int argc, char* argv[])
{
  QElapsedTimer t;
  t.start();

  qDebug() << "[boot] bootDatabase() start";
  bootDatabase();
  qDebug() << "[boot] bootDatabase() done —" << t.elapsed() << "ms";

  qDebug() << "[boot] bootQmlLinkage() start";
  bootQmlLinkage();
  qDebug() << "[boot] bootQmlLinkage() done —" << t.elapsed() << "ms";

  qDebug() << "[boot] loadScreens() start";
  Router::loadScreens();
  qDebug() << "[boot] loadScreens() done —" << t.elapsed() << "ms";

  qDebug() << "[boot] createApp() start";
  auto* app = createApp(argc, argv);
  qDebug() << "[boot] createApp() done (window visible) —" << t.elapsed() << "ms";

  // DEBUG-only: honour --sav/--screen/--select launch flags (no-op in release).
  applyDebugLaunch(app);

  // DEBUG-only: start the live control channel on 127.0.0.1:8766 (no-op in release).
  startDebugServer();

  return app;
}

